# Generated by Django 4.1.2 on 2022-11-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_accounts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
