# Generated by Django 4.1.2 on 2022-11-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_options_users_email_users_is_accounts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('employee_code', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
