# Generated by Django 4.1.2 on 2022-11-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_supervisior_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_add_sites_and_vendors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
    ]
