# Generated by Django 4.1.2 on 2022-10-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_req', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='requisition_date',
            field=models.DateField(),
        ),
    ]
