# Generated by Django 4.1.2 on 2022-10-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_req', '0002_alter_materials_requisition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='requisition_date',
            field=models.CharField(max_length=50),
        ),
    ]
