# Generated by Django 4.1.2 on 2022-10-26 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_req', '0003_alter_materials_requisition_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materials',
            new_name='MaterialReq',
        ),
    ]
