# Generated by Django 4.1.2 on 2022-11-09 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_alter_sites_city_alter_sites_country_and_more'),
        ('material_req', '0006_alter_materialreq_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialreq',
            name='site_id',
        ),
        migrations.AddField(
            model_name='materialreq',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.sites'),
        ),
    ]
