# Generated by Django 4.1.2 on 2022-10-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('alias_name', models.CharField(max_length=20)),
                ('quantity', models.CharField(default=1.0, max_length=20)),
                ('conversion_quantity', models.CharField(default=0.0, max_length=20)),
                ('gst_rate', models.CharField(default=0.0, max_length=20)),
                ('allowable_tolerance', models.CharField(default=0.0, max_length=20)),
            ],
        ),
    ]
