# Generated by Django 4.1.2 on 2022-11-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_state_options_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='zipcode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
