# Generated by Django 4.1.2 on 2022-11-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cin_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='gstin',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='pan_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='pincode',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='street',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='street2',
            field=models.CharField(max_length=200),
        ),
    ]
