# Generated by Django 4.1.2 on 2022-11-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendors',
            options={'ordering': ['vendor_code']},
        ),
    ]
