# Generated by Django 4.1.2 on 2022-11-07 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_alter_city_zipcode'),
        ('vendors', '0003_alter_vendors_country_alter_vendors_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.city'),
        ),
    ]
