# Generated by Django 4.1.2 on 2022-10-28 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_no', models.CharField(max_length=20)),
                ('site_desc', models.CharField(max_length=200)),
                ('alias_name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('street2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
            ],
        ),
    ]
