# Generated by Django 4.1.2 on 2022-11-02 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('sites', '0004_alter_sites_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients'),
        ),
    ]
