# Generated by Django 4.1.2 on 2022-11-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_alter_city_zipcode'),
        ('sites', '0007_alter_sites_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.city'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.country'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.state'),
        ),
    ]
